services:
  mysql:
    image: mysql:8.4
    container_name: simple-drive-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_drive
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - simple-drive-mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci

volumes:
  simple-drive-mysql-data:
